apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api-deploy
  labels:
    app: udagram-feed-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-api-app
  template:
    metadata:
      name: udagram-feed-api-pod
      labels:
        app: udagram-feed-api-app # Pod label
    spec:
      containers:
      - name: udagram-feed-api
        image: docker.io/suneetsinghrana/udagram-feed-api:latest
        env:
        - name: AWS_BUCKET
          value: "udagram-suneet-dev"
        - name: AWS_PROFILE
          value: "default"
        - name: AWS_REGION
          value: "us-east-1"
        - name: URL
          value: "http://localhost:8100"
        - name: JWT_SECRET
          value: "suneetsinghrana"
        - name: POSTGRES_DB
          value: "udagramDB"
        - name: POSTGRES_HOST
          value: "udagramdevdb.cgrjultsx5tx.us-east-1.rds.amazonaws.com"
        - name: POSTGRES_PASSWORD
          value: "udagramdevdb"
        - name: POSTGRES_USERNAME
          value: "udagramdevdb"
        ports:
        - containerPort: 8080