apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feed-api-app
  labels:
    app: udagram-feed-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-feed-api-app
  template:
    metadata:
      labels:
        app: udagram-feed-api-app
    spec:
      containers:
      - name: udagram-feed-api
        image: suneetsinghrana/udagram-feed-api
        ports:
        - containerPort: 8081