apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api-app
  labels:
    run: udagram-feed-api-app
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: udagram-feed-api-app