apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api-svc
  labels:
    app: udagram-feed-api-app
spec:
  #type: NodePort # Default is ClusterIP if not specified
  selector:
    app: udagram-feed-api-app # match the Pod label
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    #targetPort: 80 # targetPort is optional if same as port number
    protocol: TCP